# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kerkdiensten', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kerken',
            options={'verbose_name_plural': 'kerken'},
        ),
        migrations.AlterModelOptions(
            name='user_details',
            options={'verbose_name_plural': 'user_details'},
        ),
        migrations.AddField(
            model_name='user_details',
            name='rollen',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
