# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kerkdiensten', '0002_auto_20161128_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rollen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollen', models.CharField(max_length=256)),
                ('rol_id', models.CharField(max_length=64)),
            ],
        ),
    ]
