# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kerkdiensten', '0003_rollen'),
    ]

    operations = [
        migrations.CreateModel(
            name='DienstSoorten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'dienstsoorten',
            },
        ),
        migrations.CreateModel(
            name='Kerkdiensten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('kerk', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kerkdiensten.Kerken')),
                ('soort_dienst', models.ForeignKey(default='kerkdienst', on_delete=django.db.models.deletion.CASCADE, to='kerkdiensten.DienstSoorten')),
            ],
        ),
        migrations.AlterModelOptions(
            name='rollen',
            options={'verbose_name_plural': 'rollen'},
        ),
    ]
