# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kerkdiensten', '0004_auto_20161202_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kerkdiensten',
            options={'verbose_name_plural': 'kerkdiensten'},
        ),
        migrations.AlterField(
            model_name='kerkdiensten',
            name='start_time',
            field=models.DateField(),
        ),
    ]
