# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kerkdiensten', '0005_auto_20161202_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollen',
            name='beschikbaarheid',
            field=models.BooleanField(default=False),
        ),
    ]
