# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 19:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kerkdiensten', '0006_rollen_beschikbaarheid'),
    ]

    operations = [
        migrations.AddField(
            model_name='kerkdiensten',
            name='beschikbaar',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
