# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 20:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kerkdiensten', '0007_kerkdiensten_beschikbaar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='rollen_v2',
            field=models.ManyToManyField(blank=True, to='kerkdiensten.Rollen'),
        ),
        migrations.AlterField(
            model_name='kerkdiensten',
            name='beschikbaar',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
