# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kerkdiensten', '0011_userroll'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userroll',
            options={'verbose_name_plural': 'UserRoll'},
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='rollen',
        ),
    ]
