# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kerkdiensten', '0012_auto_20161228_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kerkdiensten',
            name='beschikbaar',
        ),
        migrations.AddField(
            model_name='kerkdiensten',
            name='beschikbaar',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kerkdiensten.UserRoll'),
        ),
    ]
