# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kerkdiensten', '0013_auto_20161228_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kerkdiensten',
            name='beschikbaar',
        ),
        migrations.AddField(
            model_name='kerkdiensten',
            name='beschikbaar',
            field=models.ManyToManyField(default=None, to='kerkdiensten.UserRoll'),
        ),
    ]
