# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-30 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kerkdiensten', '0015_auto_20161230_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kerkdiensten',
            name='beschikbaar',
            field=models.ManyToManyField(blank=True, default=None, related_name='kerkdienst_beschikbaar', to='kerkdiensten.UserRoll'),
        ),
        migrations.AlterField(
            model_name='kerkdiensten',
            name='ingeroosterd',
            field=models.ManyToManyField(blank=True, default=None, related_name='kerkdienst_ingeroosterd', to='kerkdiensten.UserRoll'),
        ),
    ]
