# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kerkdiensten', '0016_auto_20161230_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='kerkdiensten',
            name='beschikbaarheid_open',
            field=models.BooleanField(default=True),
        ),
    ]
