# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kerkdiensten', '0018_instrument'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instrument',
            new_name='Instrumenten',
        ),
    ]
