# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kerkdiensten', '0019_auto_20170102_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumenten',
            options={'verbose_name_plural': 'Instrumenten'},
        ),
    ]
