# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kerkdiensten', '0020_auto_20170102_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroll',
            name='instrument',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kerkdiensten.Instrumenten'),
        ),
    ]
