# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kerkdiensten', '0023_auto_20170102_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroll',
            name='instrument',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='kerkdiensten.Instrumenten'),
        ),
    ]
