# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kerkdiensten', '0027_auto_20170102_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userroll',
            name='instrument',
        ),
    ]
