# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kerkdiensten', '0029_delete_instrumenten'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumenten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'instrumenten',
            },
        ),
    ]
