# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kerkdiensten', '0032_auto_20170102_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='userrollen',
            field=models.ManyToManyField(blank=True, related_name='user_details_userrollen', to='kerkdiensten.UserRoll'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='rollen_v2',
            field=models.ManyToManyField(blank=True, related_name='user_details_rollen_v2', to='kerkdiensten.Rollen'),
        ),
    ]
