# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kerkdiensten', '0033_auto_20170103_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='userrollen',
        ),
    ]
