# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kerkdiensten', '0034_remove_user_details_userrollen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='instrumenten',
            field=models.ManyToManyField(blank=True, related_name='user_details_instrumenten', to='kerkdiensten.Instrumenten'),
        ),
    ]
