# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kerkdiensten', '0035_user_details_instrumenten'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='instrumenten',
        ),
    ]
