# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kerkdiensten', '0036_remove_user_details_instrumenten'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuziekTeams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=256)),
                ('leden', models.ManyToManyField(blank=True, to='kerkdiensten.UserRoll')),
            ],
        ),
    ]
