# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kerkdiensten', '0037_muziekteams'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='muziekteams',
            options={'verbose_name_plural': 'MuziekTeams'},
        ),
    ]
