# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-13 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kerkdiensten', '0038_auto_20170103_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='kerk',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='kerkdiensten.Kerken'),
        ),
    ]
