# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-13 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kerkdiensten', '0039_auto_20170213_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='kerk',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='kerkdiensten.Kerken'),
        ),
    ]
